import json

def categories():

    categories_string = """
    
    {
    "arts and crafts": [
        "arranging flowers",
        "blowing glass",
        "brush painting",
        "carving pumpkin",
        "clay pottery making",
        "decorating the christmas tree",
        "drawing",
        "getting a tattoo",
        "knitting",
        "making jewelry",
        "spray painting",
        "weaving basket"
    ],
    "athletics - jumping": [
        "high jump",
        "hurdling",
        "long jump",
        "parkour",
        "pole vault",
        "triple jump"
    ],
    "athletics - throwing + launching": [
        "archery",
        "catching or throwing frisbee",
        "disc golfing",
        "hammer throw",
        "javelin throw",
        "shot put",
        "throwing axe",
        "throwing ball",
        "throwing discus"
    ],
    "auto maintenance": [
        "changing oil",
        "changing wheel",
        "checking tires",
        "pumping gas"
    ],
    "ball sports": [
        "bowling",
        "catching or throwing baseball",
        "catching or throwing softball",
        "dodgeball",
        "dribbling basketball",
        "dunking basketball",
        "golf chipping",
        "golf driving",
        "golf putting",
        "hitting baseball",
        "hurling (sport)",
        "juggling soccer ball",
        "kicking field goal",
        "kicking soccer ball",
        "passing American football (in game)",
        "passing American football (not in game)",
        "playing basketball",
        "playing cricket",
        "playing kickball",
        "playing squash or racquetball",
        "playing tennis",
        "playing volleyball",
        "shooting basketball",
        "shooting goal (soccer)",
        "shot put"
    ],
    "body motions": [
        "air drumming",
        "applauding",
        "baby waking up",
        "bending back",
        "clapping",
        "cracking neck",
        "drumming fingers",
        "finger snapping",
        "headbanging",
        "headbutting",
        "pumping fist",
        "shaking head",
        "stretching arm",
        "stretching leg",
        "swinging legs"
    ],
    "cleaning": [
        "cleaning floor",
        "cleaning gutters",
        "cleaning pool",
        "cleaning shoes",
        "cleaning toilet",
        "cleaning windows",
        "doing laundry",
        "making bed",
        "mopping floor",
        "setting table",
        "shining shoes",
        "sweeping floor",
        "washing dishes"
    ],
    "cloths": [
        "bandaging",
        "doing laundry",
        "folding clothes",
        "folding napkins",
        "ironing",
        "making bed",
        "tying bow tie",
        "tying knot (not on a tie)",
        "tying tie"
    ],
    "communication": [
        "answering questions",
        "auctioning",
        "bartending",
        "celebrating",
        "crying",
        "giving or receiving award",
        "laughing",
        "news anchoring",
        "presenting weather forecast",
        "sign language interpreting",
        "testifying"
    ],
    "cooking": [
        "baking cookies",
        "barbequing",
        "breading or breadcrumbing",
        "cooking chicken",
        "cooking egg",
        "cooking on campfire",
        "cooking sausages",
        "cutting pineapple",
        "cutting watermelon",
        "flipping pancake",
        "frying vegetables",
        "grinding meat",
        "making a cake",
        "making a sandwich",
        "making pizza",
        "making sushi",
        "making tea",
        "peeling apples",
        "peeling potatoes",
        "picking fruit",
        "scrambling eggs",
        "tossing salad"
    ],
    "dancing": [
        "belly dancing",
        "breakdancing",
        "cheerleading",
        "country line dancing",
        "dancing ballet",
        "dancing charleston",
        "dancing gangnam style",
        "dancing macarena",
        "jumpstyle dancing",
        "krumping",
        "marching",
        "robot dancing",
        "salsa dancing",
        "swing dancing",
        "tango dancing",
        "tap dancing",
        "zumba"
    ],
    "eating + drinking": [
        "bartending",
        "dining",
        "drinking",
        "drinking beer",
        "drinking shots",
        "eating burger",
        "eating cake",
        "eating carrots",
        "eating chips",
        "eating doughnuts",
        "eating hotdog",
        "eating ice cream",
        "eating spaghetti",
        "eating watermelon",
        "opening bottle",
        "tasting beer",
        "tasting food"
    ],
    "electronics": [
        "assembling computer",
        "playing controller",
        "texting",
        "using computer",
        "using remote controller (not gaming)"
    ],
    "garden + plants": [
        "blowing leaves",
        "carving pumpkin",
        "chopping wood",
        "climbing tree",
        "decorating the christmas tree",
        "egg hunting",
        "mowing lawn",
        "planting trees",
        "trimming trees",
        "watering plants"
    ],
    "golf": [
        "golf chipping",
        "golf driving",
        "golf putting"
    ],
    "gymnastics": [
        "bouncing on trampoline",
        "cartwheeling",
        "gymnastics tumbling",
        "somersaulting",
        "vault"
    ],
    "hair": [
        "braiding hair",
        "brushing hair",
        "curling hair",
        "dying hair",
        "fixing hair",
        "getting a haircut",
        "shaving head",
        "shaving legs",
        "trimming or shaving beard",
        "washing hair",
        "waxing back",
        "waxing chest",
        "waxing eyebrows",
        "waxing legs"
    ],
    "hands": [
        "air drumming",
        "applauding",
        "clapping",
        "cutting nails",
        "doing nails",
        "drumming fingers",
        "finger snapping",
        "pumping fist",
        "washing hands"
    ],
    "head + mouth": [
        "balloon blowing",
        "beatboxing",
        "blowing nose",
        "blowing out candles",
        "brushing teeth",
        "gargling",
        "headbanging",
        "headbutting",
        "shaking head",
        "singing",
        "smoking",
        "smoking hookah",
        "sneezing",
        "sniffing",
        "sticking tongue out",
        "whistling",
        "yawning"
    ],
    "heights": [
        "abseiling",
        "bungee jumping",
        "climbing a rope",
        "climbing ladder",
        "climbing tree",
        "diving cliff",
        "ice climbing",
        "jumping into pool",
        "paragliding",
        "rock climbing",
        "skydiving",
        "slacklining",
        "springboard diving",
        "swinging on something",
        "trapezing"
    ],
    "interacting with animals": [
        "bee keeping",
        "catching fish",
        "feeding birds",
        "feeding fish",
        "feeding goats",
        "grooming dog",
        "grooming horse",
        "holding snake",
        "ice fishing",
        "milking cow",
        "petting animal (not cat)",
        "petting cat",
        "riding camel",
        "riding elephant",
        "riding mule",
        "riding or walking with horse",
        "shearing sheep",
        "training dog",
        "walking the dog"
    ],
    "juggling": [
        "contact juggling",
        "hula hooping",
        "juggling balls",
        "juggling fire",
        "juggling soccer ball",
        "spinning poi"
    ],
    "makeup": [
        "applying cream",
        "doing nails",
        "dying hair",
        "filling eyebrows",
        "getting a tattoo"
    ],
    "martial arts": [
        "arm wrestling",
        "capoeira",
        "drop kicking",
        "high kick",
        "punching bag",
        "punching person (boxing)",
        "side kick",
        "sword fighting",
        "tai chi",
        "wrestling"
    ],
    "miscellaneous": [
        "digging",
        "extinguishing fire",
        "garbage collecting",
        "laying bricks",
        "moving furniture",
        "spraying",
        "stomping grapes",
        "tapping pen",
        "unloading truck"
    ],
    "mobility - land": [
        "crawling baby",
        "driving car",
        "driving tractor",
        "faceplanting",
        "hoverboarding",
        "jogging",
        "motorcycling",
        "parkour",
        "pushing car",
        "pushing cart",
        "pushing wheelchair",
        "riding a bike",
        "riding mountain bike",
        "riding scooter",
        "riding unicycle",
        "roller skating",
        "running on treadmill",
        "skateboarding",
        "surfing crowd",
        "using segway",
        "waiting in line"
    ],
    "music": [
        "beatboxing",
        "busking",
        "playing accordion",
        "playing bagpipes",
        "playing bass guitar",
        "playing cello",
        "playing clarinet",
        "playing cymbals",
        "playing didgeridoo",
        "playing drums",
        "playing flute",
        "playing guitar",
        "playing harmonica",
        "playing harp",
        "playing keyboard",
        "playing organ",
        "playing piano",
        "playing recorder",
        "playing saxophone",
        "playing trombone",
        "playing trumpet",
        "playing ukulele",
        "playing violin",
        "playing xylophone",
        "recording music",
        "singing",
        "strumming guitar",
        "tapping guitar",
        "whistling"
    ],
    "paper": [
        "bookbinding",
        "counting money",
        "folding napkins",
        "folding paper",
        "opening present",
        "reading book",
        "reading newspaper",
        "ripping paper",
        "shredding paper",
        "unboxing",
        "wrapping present",
        "writing"
    ],
    "personal hygiene": [
        "brushing teeth",
        "taking a shower",
        "trimming or shaving beard",
        "washing feet",
        "washing hair",
        "washing hands"
    ],
    "playing games": [
        "egg hunting",
        "flying kite",
        "hopscotch",
        "playing cards",
        "playing chess",
        "playing monopoly",
        "playing paintball",
        "playing poker",
        "riding mechanical bull",
        "rock scissors paper",
        "shuffling cards",
        "skipping rope",
        "tossing coin"
    ],
    "racquet + bat sports": [
        "catching or throwing baseball",
        "catching or throwing softball",
        "hitting baseball",
        "hurling (sport)",
        "playing badminton",
        "playing cricket",
        "playing squash or racquetball",
        "playing tennis"
    ],
    "snow + ice": [
        "biking through snow",
        "bobsledding",
        "hockey stop",
        "ice climbing",
        "ice fishing",
        "ice skating",
        "making snowman",
        "playing ice hockey",
        "shoveling snow",
        "ski jumping",
        "skiing (not slalom or crosscountry)",
        "skiing crosscountry",
        "skiing slalom",
        "sled dog racing",
        "snowboarding",
        "snowkiting",
        "snowmobiling",
        "tobogganing"
    ],
    "swimming": [
        "swimming backstroke",
        "swimming breast stroke",
        "swimming butterfly stroke"
    ],
    "touching person": [
        "carrying baby",
        "hugging",
        "kissing",
        "massaging back",
        "massaging feet",
        "massaging legs",
        "massaging person's head",
        "shaking hands",
        "slapping",
        "tickling"
    ],
    "using tools": [
        "bending metal",
        "blasting sand",
        "building cabinet",
        "building shed",
        "changing oil",
        "changing wheel",
        "checking tires",
        "plastering",
        "pumping gas",
        "sanding floor",
        "sharpening knives",
        "sharpening pencil",
        "welding"
    ],
    "mobility - water": [
        "crossing river",
        "diving cliff",
        "jumping into pool",
        "scuba diving",
        "snorkeling",
        "springboard diving",
        "swimming backstroke",
        "swimming breast stroke",
        "swimming butterfly stroke",
        "water sliding"
    ],
    "water sports": [
        "canoeing or kayaking",
        "jetskiing",
        "kitesurfing",
        "parasailing",
        "sailing",
        "surfing water",
        "water skiing",
        "windsurfing"
    ],
    "waxing": [
        "waxing back",
        "waxing chest",
        "waxing eyebrows",
        "waxing legs"
    ],
    "custom": [
        "pull ups",
        "bench pressing",
        "yoga",
        "snatch weight lifting",
        "front raises",
        "squat",
        "exercising arm",
        "deadlifting",
        "lunge",
        "situp",
        "doing aerobics",
        "clean and jerk",
        "push up",
        "exercising with an exercise ball"
    ]
}

    
    
    """
    
   
    categories = json.loads(categories_string)

    return categories
        
def classes():
    classes_string = """
    [
  "abseiling",
  "air drumming",
  "answering questions",
  "applauding",
  "applying cream",
  "archery",
  "arm wrestling",
  "arranging flowers",
  "assembling computer",
  "auctioning",
  "baby waking up",
  "baking cookies",
  "balloon blowing",
  "bandaging",
  "barbequing",
  "bartending",
  "beatboxing",
  "bee keeping",
  "belly dancing",
  "bench pressing",
  "bending back",
  "bending metal",
  "biking through snow",
  "blasting sand",
  "blowing glass",
  "blowing leaves",
  "blowing nose",
  "blowing out candles",
  "bobsledding",
  "bookbinding",
  "bouncing on trampoline",
  "bowling",
  "braiding hair",
  "breading or breadcrumbing",
  "breakdancing",
  "brush painting",
  "brushing hair",
  "brushing teeth",
  "building cabinet",
  "building shed",
  "bungee jumping",
  "busking",
  "canoeing or kayaking",
  "capoeira",
  "carrying baby",
  "cartwheeling",
  "carving pumpkin",
  "catching fish",
  "catching or throwing baseball",
  "catching or throwing frisbee",
  "catching or throwing softball",
  "celebrating",
  "changing oil",
  "changing wheel",
  "checking tires",
  "cheerleading",
  "chopping wood",
  "clapping",
  "clay pottery making",
  "clean and jerk",
  "cleaning floor",
  "cleaning gutters",
  "cleaning pool",
  "cleaning shoes",
  "cleaning toilet",
  "cleaning windows",
  "climbing a rope",
  "climbing ladder",
  "climbing tree",
  "contact juggling",
  "cooking chicken",
  "cooking egg",
  "cooking on campfire",
  "cooking sausages",
  "counting money",
  "country line dancing",
  "cracking neck",
  "crawling baby",
  "crossing river",
  "crying",
  "curling hair",
  "cutting nails",
  "cutting pineapple",
  "cutting watermelon",
  "dancing ballet",
  "dancing charleston",
  "dancing gangnam style",
  "dancing macarena",
  "deadlifting",
  "decorating the christmas tree",
  "digging",
  "dining",
  "disc golfing",
  "diving cliff",
  "dodgeball",
  "doing aerobics",
  "doing laundry",
  "doing nails",
  "drawing",
  "dribbling basketball",
  "drinking",
  "drinking beer",
  "drinking shots",
  "driving car",
  "driving tractor",
  "drop kicking",
  "drumming fingers",
  "dunking basketball",
  "dying hair",
  "eating burger",
  "eating cake",
  "eating carrots",
  "eating chips",
  "eating doughnuts",
  "eating hotdog",
  "eating ice cream",
  "eating spaghetti",
  "eating watermelon",
  "egg hunting",
  "exercising arm",
  "exercising with an exercise ball",
  "extinguishing fire",
  "faceplanting",
  "feeding birds",
  "feeding fish",
  "feeding goats",
  "filling eyebrows",
  "finger snapping",
  "fixing hair",
  "flipping pancake",
  "flying kite",
  "folding clothes",
  "folding napkins",
  "folding paper",
  "front raises",
  "frying vegetables",
  "garbage collecting",
  "gargling",
  "getting a haircut",
  "getting a tattoo",
  "giving or receiving award",
  "golf chipping",
  "golf driving",
  "golf putting",
  "grinding meat",
  "grooming dog",
  "grooming horse",
  "gymnastics tumbling",
  "hammer throw",
  "headbanging",
  "headbutting",
  "high jump",
  "high kick",
  "hitting baseball",
  "hockey stop",
  "holding snake",
  "hopscotch",
  "hoverboarding",
  "hugging",
  "hula hooping",
  "hurdling",
  "hurling (sport)",
  "ice climbing",
  "ice fishing",
  "ice skating",
  "ironing",
  "javelin throw",
  "jetskiing",
  "jogging",
  "juggling balls",
  "juggling fire",
  "juggling soccer ball",
  "jumping into pool",
  "jumpstyle dancing",
  "kicking field goal",
  "kicking soccer ball",
  "kissing",
  "kitesurfing",
  "knitting",
  "krumping",
  "laughing",
  "laying bricks",
  "long jump",
  "lunge",
  "making a cake",
  "making a sandwich",
  "making bed",
  "making jewelry",
  "making pizza",
  "making snowman",
  "making sushi",
  "making tea",
  "marching",
  "massaging back",
  "massaging feet",
  "massaging legs",
  "massaging person's head",
  "milking cow",
  "mopping floor",
  "motorcycling",
  "moving furniture",
  "mowing lawn",
  "news anchoring",
  "opening bottle",
  "opening present",
  "paragliding",
  "parasailing",
  "parkour",
  "passing American football (in game)",
  "passing American football (not in game)",
  "peeling apples",
  "peeling potatoes",
  "petting animal (not cat)",
  "petting cat",
  "picking fruit",
  "planting trees",
  "plastering",
  "playing accordion",
  "playing badminton",
  "playing bagpipes",
  "playing basketball",
  "playing bass guitar",
  "playing cards",
  "playing cello",
  "playing chess",
  "playing clarinet",
  "playing controller",
  "playing cricket",
  "playing cymbals",
  "playing didgeridoo",
  "playing drums",
  "playing flute",
  "playing guitar",
  "playing harmonica",
  "playing harp",
  "playing ice hockey",
  "playing keyboard",
  "playing kickball",
  "playing monopoly",
  "playing organ",
  "playing paintball",
  "playing piano",
  "playing poker",
  "playing recorder",
  "playing saxophone",
  "playing squash or racquetball",
  "playing tennis",
  "playing trombone",
  "playing trumpet",
  "playing ukulele",
  "playing violin",
  "playing volleyball",
  "playing xylophone",
  "pole vault",
  "presenting weather forecast",
  "pull ups",
  "pumping fist",
  "pumping gas",
  "punching bag",
  "punching person (boxing)",
  "push up",
  "pushing car",
  "pushing cart",
  "pushing wheelchair",
  "reading book",
  "reading newspaper",
  "recording music",
  "riding a bike",
  "riding camel",
  "riding elephant",
  "riding mechanical bull",
  "riding mountain bike",
  "riding mule",
  "riding or walking with horse",
  "riding scooter",
  "riding unicycle",
  "ripping paper",
  "robot dancing",
  "rock climbing",
  "rock scissors paper",
  "roller skating",
  "running on treadmill",
  "sailing",
  "salsa dancing",
  "sanding floor",
  "scrambling eggs",
  "scuba diving",
  "setting table",
  "shaking hands",
  "shaking head",
  "sharpening knives",
  "sharpening pencil",
  "shaving head",
  "shaving legs",
  "shearing sheep",
  "shining shoes",
  "shooting basketball",
  "shooting goal (soccer)",
  "shot put",
  "shoveling snow",
  "shredding paper",
  "shuffling cards",
  "side kick",
  "sign language interpreting",
  "singing",
  "situp",
  "skateboarding",
  "ski jumping",
  "skiing (not slalom or crosscountry)",
  "skiing crosscountry",
  "skiing slalom",
  "skipping rope",
  "skydiving",
  "slacklining",
  "slapping",
  "sled dog racing",
  "smoking",
  "smoking hookah",
  "snatch weight lifting",
  "sneezing",
  "sniffing",
  "snorkeling",
  "snowboarding",
  "snowkiting",
  "snowmobiling",
  "somersaulting",
  "spinning poi",
  "spray painting",
  "spraying",
  "springboard diving",
  "squat",
  "sticking tongue out",
  "stomping grapes",
  "stretching arm",
  "stretching leg",
  "strumming guitar",
  "surfing crowd",
  "surfing water",
  "sweeping floor",
  "swimming backstroke",
  "swimming breast stroke",
  "swimming butterfly stroke",
  "swing dancing",
  "swinging legs",
  "swinging on something",
  "sword fighting",
  "tai chi",
  "taking a shower",
  "tango dancing",
  "tap dancing",
  "tapping guitar",
  "tapping pen",
  "tasting beer",
  "tasting food",
  "testifying",
  "texting",
  "throwing axe",
  "throwing ball",
  "throwing discus",
  "tickling",
  "tobogganing",
  "tossing coin",
  "tossing salad",
  "training dog",
  "trapezing",
  "trimming or shaving beard",
  "trimming trees",
  "triple jump",
  "tying bow tie",
  "tying knot (not on a tie)",
  "tying tie",
  "unboxing",
  "unloading truck",
  "using computer",
  "using remote controller (not gaming)",
  "using segway",
  "vault",
  "waiting in line",
  "walking the dog",
  "washing dishes",
  "washing feet",
  "washing hair",
  "washing hands",
  "water skiing",
  "water sliding",
  "watering plants",
  "waxing back",
  "waxing chest",
  "waxing eyebrows",
  "waxing legs",
  "weaving basket",
  "welding",
  "whistling",
  "windsurfing",
  "wrapping present",
  "wrestling",
  "writing",
  "yawning",
  "yoga",
  "zumba"
]
    """
    
    classes = json.loads(classes_string)
    return classes

def sport_categories():
    return ['athletics - jumping','athletics - throwing + launching','ball sports','golf',
                        'gymnastics','heights','martial arts','racquet + bat sports','snow + ice','swimming',
                       'mobility - water', 'water sports','custom']
   
    